### PR TITLE
Gui support

### PR DESCRIPTION
**Pull request by sShaAanGg**
Currently it supports opening and saving the selected image. The buttons have no actual effect.

screenshot

### CODE REVIEW

**Comment by tsm55555** [comment]
I will check it out later tonight

**Comment by sShaAanGg** [comment]
I think it's ready for merge

**Comment by tsm55555** [comment]
it doesn't run on my device, any idea?

image

**Comment by sShaAanGg** [comment]
> it doesn't run on my device, any idea?
> 

I am building this project on Ubuntu-20.04 in virtual machine; perhaps it's an environment incompatibility issue?

It's the environment which this project are built on  
OS: Ubuntu-20.04
kernel version: 5.10.102.1-microsoft-standard-WSL2

**Comment by tsm55555** [comment]
i will try to run it on my machine

**Comment by sShaAanGg** [comment]
screenshot

It still works in my Win10 environment.

**Pull request closed without merging**
